version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: backend_dinacom_redis
    ports:
      - "6379:6379"
    networks:
      - backend_dinacom_network
    restart: unless-stopped
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
  postgres:
    image: postgres:15-alpine
    container_name: backend_dinacom_postgress
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_dinacom
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_dinacom_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d backend_dinacom"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_dinacom_api
    environment:
      APP_NAME: "Backend Dinacom"
      APP_ENV: production
      APP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: backend_dinacom
      DB_SSL_MODE: disable
      DB_TIMEZONE: Asia/Jakarta
      JWT_SECRET: fsnfuishfiusuifuies
      JWT_EXPIRE_HOURS: 24
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_dinacom_network
    restart: unless-stopped

networks:
  backend_dinacom_network:
    driver: bridge

volumes:
  postgres_data: