basePath: /api/v1
definitions:
  request.CreateRoleRequest:
    properties:
      name:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - name
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.RegisterRequest:
    properties:
      date_of_birth:
        type: string
      email:
        type: string
      gender:
        minLength: 1
        type: string
      name:
        minLength: 3
        type: string
      password:
        type: string
    required:
    - date_of_birth
    - email
    - gender
    - name
    - password
    type: object
  request.UpdateRoleRequest:
    properties:
      name:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - name
    type: object
  response.ErrorResponse:
    properties:
      error: {}
      message:
        example: Internal Server Error
        type: string
      success:
        example: false
        type: boolean
    type: object
  response.SuccessResponse:
    properties:
      data: {}
      message:
        example: data retrieved/created/updated/deleted successfully
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: Dokumentasi API untuk Nutrione
  title: NutriOne API
  version: "1.0"
paths:
  /auth/login:
    post:
      description: User Login endpoint
      parameters:
      - description: Login Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      description: User register endpoint
      parameters:
      - description: Register Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Register
      tags:
      - Auth
  /auth/strava/redirect:
    get:
      description: Access this endpoint to Integrate with strava
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Strava integrate Redirect
      tags:
      - Auth
  /role/{id}/update:
    patch:
      description: Update a Role data
      parameters:
      - description: Role update data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update Role
      tags:
      - Roles (Admin)
  /roles:
    get:
      description: get all roles data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get All Roles
      tags:
      - Roles (Admin)
  /roles/{id}:
    delete:
      description: Delete role by roleID
      parameters:
      - description: role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete role by roleID
      tags:
      - Roles (Admin)
  /roles/create:
    post:
      consumes:
      - application/json
      description: Create a new role
      parameters:
      - description: Role create data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create new role
      tags:
      - Roles (Admin)
swagger: "2.0"
